# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_Save.setEnabled(False)
        self.PushButton_Save.setGeometry(QtCore.QRect(20, 340, 151, 41))
        self.PushButton_Save.setObjectName("PushButton_Save")
        self.PushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_Exit.setGeometry(QtCore.QRect(230, 340, 151, 41))
        self.PushButton_Exit.setObjectName("PushButton_Exit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 139, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VerticalLayout_Key = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VerticalLayout_Key.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayout_Key.setObjectName("VerticalLayout_Key")
        self.Label_Address_Key = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Label_Address_Key.setFont(font)
        self.Label_Address_Key.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_Address_Key.setObjectName("Label_Address_Key")
        self.VerticalLayout_Key.addWidget(self.Label_Address_Key)
        self.Label_Port_Key = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Label_Port_Key.setFont(font)
        self.Label_Port_Key.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_Port_Key.setObjectName("Label_Port_Key")
        self.VerticalLayout_Key.addWidget(self.Label_Port_Key)
        self.Label_RunningMode_Key = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Label_RunningMode_Key.setFont(font)
        self.Label_RunningMode_Key.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_RunningMode_Key.setObjectName("Label_RunningMode_Key")
        self.VerticalLayout_Key.addWidget(self.Label_RunningMode_Key)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 30, 231, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VerticalLayout_Value = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VerticalLayout_Value.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayout_Value.setObjectName("VerticalLayout_Value")
        self.Label_Address_Value = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Label_Address_Value.setObjectName("Label_Address_Value")
        self.VerticalLayout_Value.addWidget(self.Label_Address_Value)
        self.SpinBox_Port_Value = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.SpinBox_Port_Value.setMinimum(1)
        self.SpinBox_Port_Value.setMaximum(65535)
        self.SpinBox_Port_Value.setProperty("value", 9600)
        self.SpinBox_Port_Value.setObjectName("SpinBox_Port_Value")
        self.VerticalLayout_Value.addWidget(self.SpinBox_Port_Value)
        self.ComboBox_RunningMode_Value = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ComboBox_RunningMode_Value.setEditable(False)
        self.ComboBox_RunningMode_Value.setObjectName("ComboBox_RunningMode_Value")
        self.ComboBox_RunningMode_Value.addItem("")
        self.ComboBox_RunningMode_Value.addItem("")
        self.ComboBox_RunningMode_Value.addItem("")
        self.VerticalLayout_Value.addWidget(self.ComboBox_RunningMode_Value)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.PushButton_Exit.clicked.connect(MainWindow.PushButton_Exit_Clicked)
        self.PushButton_Save.clicked.connect(MainWindow.PushButton_Save_Clicked)
        self.Label_Address_Value.textChanged['QString'].connect(MainWindow.Label_Address_Value_TextChanged)
        self.SpinBox_Port_Value.valueChanged['QString'].connect(MainWindow.SpinBox_Port_Value_ValueChanged)
        self.ComboBox_RunningMode_Value.currentIndexChanged['int'].connect(MainWindow.ComboBox_RunningMode_Value_CurrentIndexChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Configure_Windows"))
        self.PushButton_Save.setText(_translate("MainWindow", "Save changes"))
        self.PushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.Label_Address_Key.setText(_translate("MainWindow", "Address"))
        self.Label_Port_Key.setText(_translate("MainWindow", "Port"))
        self.Label_RunningMode_Key.setText(_translate("MainWindow", "RunningMode"))
        self.Label_Address_Value.setText(_translate("MainWindow", "localhost"))
        self.ComboBox_RunningMode_Value.setItemText(0, _translate("MainWindow", "PlasticMemories"))
        self.ComboBox_RunningMode_Value.setItemText(1, _translate("MainWindow", "SingleFile"))
        self.ComboBox_RunningMode_Value.setItemText(2, _translate("MainWindow", "MultiFile"))
